import Head from 'next/head'
import {View360} from "../components";


export default function Home() {
  return (
      <div className="container">
        <Head>
          <title>360° - POC</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="w-screen h-screen bg-gray-100 flex items-center justify-center space-x-6">
            <View360 amount={29} fileName="frames/frame" extension='jpeg'/>
            <View360 amount={29} fileName="frames-360/frames" extension='jpeg'/>
        </main>
      </div>
  )
}
